### ISSUE TITLE
CI tests fail on valid (I think) catalog entries

### ISSUE THREAD

**Issue by RobertPincus** [eurec4a/eurec4a-intake#10]
In #9 the CI tests which check the existence of each entry in all the catalogs are failing on some or maybe all of the P3 files. These differ from previous entries in using the `netcdf` plugin. The tests are failing even though I can use `discover()` on items locally and can open the files via the provided URLs e.g. with xarray. 

Example 1: catalog item `p3.flight_level.P3-0117` with URL 'http://psl.noaa.gov/thredds/dodsC/Datasets/ATOMIC/data/p3/Flight-Level/Level_2/P3_Flight-Level_20200117_v0.9.nc'

**Comment by d70-t** [comment]
The issue came up do to how intake-xarray was handling netcdf and opendap. Starting with release 0.3.2 of intake-xarray and the inclusion of #16, this issues should be solved.
