### ISSUE TITLE
Remove item.discover from test

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/eurec4a-intake#102]
Is this line necessary? https://github.com/eurec4a/eurec4a-intake/blob/6bbfab8a59af878d7e8aedde9a4ce859da9dcedd/tests/test_catalog.py#L43

There is an issue with the `discover` method for JSON-typed catalog entries like proposed in #99 ([see failing test](https://github.com/eurec4a/eurec4a-intake/pull/99/checks#step:6:121)). The `discover`-method is currently not implemented, but I proposed a solution at https://github.com/intake/intake/issues/673

However, I do not see why we necessarily have to call `item.discover` anyway. Can we drop it or at least use an alternative?

Cheers!

**Comment by d70-t** [comment]
Maybe it's indeed not necessary...

**Comment by observingClouds** [comment]
This is what I thought as well. The actual test is done in the lines that follow.
@leifdenby would you agree?

**Comment by d70-t** [comment]
I gave it a try and it seems like the test are still doing something (e.g. fetching some data from the sources), but don't use `discover()` anymore.

It's a pity to get rid of it (I liked it's simplicity), but if it doesn't work, we can't use it...

**Comment by observingClouds** [comment]
Just referencing https://github.com/intake/intake/issues/673 for the json driver.
