### ISSUE TITLE
Weekly tests fail due to netCDF certificate issue

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/eurec4a-intake#121]
Just as a note, there is supposedly an [issue](https://github.com/Unidata/netcdf4-python/issues/1179) with the current netcdf4 wheel that looks like it could also cause our weekly check to fail.

I feel like this is a reoccurring error we had also a couple of months back.

**Comment by d70-t** [comment]
This is a pity... I excluded that version of netCDF4 again. I relly hope the next release of netCDF4 will not have that bug. We could of course also restrict to `<1.6.0`, but then we won't get any updates anymore...

**Comment by observingClouds** [comment]
Closing for now as it is fixed by #122

**Comment by observingClouds** [comment]
A new version of netCDF4-python (1.6.2) has been released, but it is still causing the same troubles as described above.
According to the linked issue, an installation via conda or on a system other than linux is not causing these troubles.

For now I propose to restrict the netCDF4-python versions further in the requirements.

**Comment by observingClouds** [comment]
And it's [happening again](https://github.com/eurec4a/eurec4a-intake/actions/runs/5102196921/jobs/9171601891#step:5:69868)...

**Comment by observingClouds** [comment]
Fixed for now...potentially until the next netcdf version release.
