### ISSUE TITLE
Non-descriptive grid names in intake catalog (simulations)

### ISSUE THREAD

**Issue by suessspeise** [eurec4a/eurec4a-intake#123]
This concerns the [intake catalog of the grids for the EUREC4A LES simulations](eurec4a/eurec4a-intake/master/Simulations/grids.yaml).

```python
import eurec4a
grids = eurec4a.get_intake_catalog().simulations.grids
list(grids)
```
fetches this rather cryptic list:
```console
['6b59890b-99f3-939b-e76a-0a3ad2e43140',
 '3c7523ba-f78c-c23e-6654-012805ba3300',
 'ecf22d17-dcee-1510-a807-11ae4a612be0']
```
Better desriptions are available:
```python
for grid in list(grids):
    print(grids[grid].description)
```
```console
ICON LES horizontal grid of DOM01 (EUREC4A_PR1250m_DOM01)
ICON LES horizontal grid of DOM02 (EUREC4A_PR1250m_DOM02)
ICON LES vertical grid of DOM01 (EUREC4A_PR1250m_DOM01)
```
But the identifiers could also be more informative.

**Comment by d70-t** [comment]
The catalog intentionally contains the UUIDs of the grids. They are unique identifiers and are not meant to be interpreted in any way. Instead they should be used like:

```python
data = get_some_dataset()
hgrid = grids[data.uuidOfHGrid].to_dask()
vgrid = grids[data.uuidOfVGrid].to_dask()
```

By using non-descriptive opaque identifiers, it's easier not to accidentally have two different grids which end up having the same name.

**Comment by suessspeise** [comment]
fair enough 😢
