### ISSUE TITLE
Issue with files hosted by the NCEI openDAP-server

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/eurec4a-intake#131]
The [weekly test](https://github.com/eurec4a/eurec4a-intake/actions/runs/3611510895) reveals that some P3 WSRA datasets cannot be loaded any longer via openDAP due to an error in the time variable. This issue is not an issue with eurec4a-intake or its dependencies.

I also tried to retrieve the time steps directly from the ncei.noaa.gov openDAP-Server without success:

# Failing example:
- https://www.ncei.noaa.gov/thredds-ocean/dodsC/psl/atomic/p3/WSRA/EUREC4A_ATOMIC_P3_WSRA_20200131_v1.0.nc.ascii?time%5B0:1:193%5D
```
Dataset {
    Int32 time[trajectory = 194];
} psl/atomic/p3/WSRA/EUREC4A_ATOMIC_P3_WSRA_20200131_v1.0.nc;
---------------------------------------------
Error {
    code = 500;
    message = "null";
};
```

# Working example:
- https://www.ncei.noaa.gov/thredds-ocean/dodsC/psl/atomic/p3/WSRA/EUREC4A_ATOMIC_P3_WSRA_20200124_v1.0.nc.ascii?time[0:1:193]
```
Dataset {
    Int32 time[trajectory = 194];
} psl/atomic/p3/WSRA/EUREC4A_ATOMIC_P3_WSRA_20200124_v1.0.nc;
---------------------------------------------
time[194]
0, 50, 100, 150, 200, 270, 320, 370, 420, 470, 540, 590, 640, 690, 740, 810, 860, 910, 960, 1010, 1080, 1130, 1180, 1230, 1280, 1350, 1400, 1450, 1500, 1550, 1620, 1670, 1720, 1770, 1820, 1890, 1940, 1990, 2040, 2090, 2160, 2210, 2260, 2310, 2360, 2430, 2480, 2530, 2580, 2630, 2700, 2750, 2800, 2850, 2900, 2970, 3020, 3070, 3120, 3170, 3240, 3290, 3340, 3390, 3440, 3510, 3560, 3610, 3660, 3710, 3780, 3830, 3880, 3930, 3980, 4050, 4100, 4150, 4200, 4250, 4320, 4371, 4421, 4471, 4521, 4591, 4641, 4691, 4741, 4791, 4861, 4911, 4961, 5011, 5061, 5131, 5181, 5231, 5281, 5331, 5401, 5451, 5501, 5551, 5601, 5671, 5721, 5771, 5821, 5871, 5941, 5991, 6041, 6091, 6141, 6211, 6261, 6311, 6361, 6901, 6951, 7021, 7071, 7121, 7171, 7221, 7291, 7341, 7391, 7441, 7491, 7561, 7611, 7661, 7711, 7761, 7831, 7881, 7931, 7981, 8031, 8101, 8151, 8201, 8251, 8301, 8371, 8421, 8471, 8521, 8571, 8641, 8691, 8741, 8791, 8841, 8911, 8961, 9011, 9061, 9111, 9181, 9231, 9281, 9331, 9381, 9451, 9501, 9551, 9601, 9651, 9721, 9771, 9821, 10935, 10985, 11035, 11085, 11135, 11205, 11255, 11305, 11355, 11405, 11475, 11525, 11575, 11625, 11675, 11745, 11795, 11845, 11895, 11945
```

In both cases a valid netCDF file could be retrieved via the HTTP-Download. It seems therefore likely that the openDAP-Server has some issues lately to host some files correctly.

**Comment by RobertPincus** [comment]
@lbariteau this seems like a change on the NCEI server side. Can you be in contact with them and explain the issue/ask for solutions?

**Comment by lbariteau** [comment]
Ok will look into it and ping NCEI. ~ Ludovic

**Comment by observingClouds** [comment]
Just a bit of further information. My examples are not always failing/working. It seems like it is very variable. Sometimes other dates are failing too. Something seems unstable. Every test turns up other datasets that are hosted at NCEI that fail, while others work again. You could check [all the runs](https://github.com/eurec4a/eurec4a-intake/actions/runs/3611510895) if more examples are needed.

**Comment by observingClouds** [comment]
I'm closing this as the issue seems to be solved or disappeared upstream. 🤞 it is the former.
