### ISSUE TITLE
Move to default intake-xarray

### ISSUE THREAD

**Issue by RobertPincus** [eurec4a/eurec4a-intake#14]
As of commit [2016aa8](https://github.com/intake/intake-xarray/commit/2016aa87a77687de5c0d4c52a020c8a94641967e) `intake-xarray` supports generic authentication. Should we update this catalog and documentation to use the current master version rather the fork from @leifdenby ?

**Comment by d70-t** [comment]
#16 also includes the changed a released version of intake-xarray
