### ISSUE TITLE
Current issues with catalog

### ISSUE THREAD

**Issue by leifdenby** [eurec4a/eurec4a-intake#17]
The most recent commit shows that there are two issues with the catalog:

https://github.com/eurec4a/eurec4a-intake/runs/1208857361

- `barbados.bco.CORAL_LIDAR`: 500 error (internal server error)
- `halo.bahamas.ql.by_flight_id.HALO-0119`: 404 error

@d70-t any ideas what happened to the bahamas one? I'll look at the CORAL LIDAR one

**Comment by d70-t** [comment]
I think it is the AERIS opendap server. It is very very slow at the moment and almost unusable...

**Comment by leifdenby** [comment]
> I think it is the AERIS opendap server. It is very very slow at the moment and almost unusable...

Yes, I just spotted that too. Thanks! I'll wait and see what they find out

**Comment by leifdenby** [comment]
Now that AERIS is up again the tests all passed!
