### ISSUE TITLE
help for including merian data into this amazing tool :) 

### ISSUE THREAD

**Issue by ClauClouds** [eurec4a/eurec4a-intake#52]
Hi All! first of all this is not an issue :)
I am enthusiastic about this eurec4a-intake and I really would like to include the cloud radar data collected on merian into this. How does it work? I drop a question because I am lazy and not confident at all in my capabilities in dealing with github. The data are already on Aeris and I have some plotting routines ready with which I prepared these quicklooks. https://atmos.meteo.uni-koeln.de/~cacquist/eurec4a/dataBrowser4.html?site=MSMerian&date=0&UpperLeft=MSMerian_reflectivity&UpperRight=MSMerian_spectral_width&LowerRight=MSMerian_ship_track&LowerLeft=MSMerian_mean_Doppler_velocity

Is there anybody there willing not to leave me alone trying to include this? many thanks in advance for help Cheers Claudia  :)

**Comment by d70-t** [comment]
Hey @ClauClouds, that is a great idea 😄 🎉

So probably the data will look similar to the cloud radar data from Meteor? @jroettenbacher prepared a pull request (#45) for that data. The idea would be that you create a fork of this repository, such that you can add a new branch where you add the required yaml files for the catalog. [Here](https://github.com/eurec4a/eurec4a-intake/pull/45/files) you can see the files which have been added for the cloud radar on the Meteor. After adding them, you can test your own local catalog if it is working using something like:

```python
import intake
cat = intake.open_catalog("catalog.yml")
cat.Meteor.LIMRAD94.high_res.to_dask()
```
```
<xarray.Dataset>
Dimensions:                    (chirp: 3, range: 367, time: 44447)
Coordinates:
  * time                       (time) datetime64[ns] 2020-02-01T00:00:06.7000...
  * range                      (range) float32 313.0 335.4 ... 1.296e+04
[...]
```

Once that looks ok, you can commit and push your changes and create a pull request into this repository. We'll have a little review on your changes and after everything is settled, your additions will be merged and they will be available in the catalog.

As a next step, it would be great to introduce the dataset into the [How to Eurec4a Book](https://eurec4a.pages.gwdg.de/how_to_eurec4a/intro.html) it can be something small like just a simple plot as for the [Meteor cloudradar](https://eurec4a.pages.gwdg.de/how_to_eurec4a/meteor_cloudradar.html) or something more involved as [the combined HAMP plot](https://eurec4a.pages.gwdg.de/how_to_eurec4a/hamp_comparison.html) which has been prepared by @MeraX or something with multiple steps as for the [JOANNE dataset](https://eurec4a.pages.gwdg.de/how_to_eurec4a/dropsondes.html).

**Comment by d70-t** [comment]
As the dataset has been included into the catalog, I'll consider this as done.
