### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by d70-t** [eurec4a/eurec4a-intake#75]
We need to find a way to speed up tests, as the catalog now (at least since #74) grows so large that re-testing everything might not be a sensible choice anymore.

Probably useful ideas:
* split tests based on data provider in order to run them in parallel and isolate errors if a provider is not reachable
* cache results of previous runs and retest only entries which have been changed since a last test run

**Comment by RobertPincus** [comment]
@d70-t I like both these ideas, but I'm not sure how to implement either of them.
